### ISSUE TITLE
Tool doesn't work

### ISSUE THREAD

**Issue by Sleeptime17** [SecurityFTW/cs-suite#18]
I set up a new GCP Debian instance, apt installed git, python2.7, python-pip, gcc, and executed
```bash
git clone https://github.com/SecurityFTW/cs-suite.git
cd cs-suite/
sudo python setup.py
```

Finishing the process with blank answers to AWS credentials:
```bash
Please enter your AWS credetionals
AWS Access Key ID [None]:
AWS Secret Access Key [None]:
Default region name [None]:
Default output format [None]:
```
(by the way, credetionals != credentials)

I wanted a GCP scan, and went by the readme's "To run GCP Audit - python cs.py -env gcp -pId <project_name>"

This is my output (censored):
```bash

test@gcp-scan:~/cs-suite$ python cs.py -env gcp -pId CENSOREDPROJ
Starting GCP Audit
/usr/local/lib/python2.7/dist-packages/oauth2client/_helpers.py:255: UserWarning                                                                                                                                                             : Cannot access creds.data: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
Traceback (most recent call last):
  File "gscout.py", line 63, in <module>
    list_projects(sys.argv[1],sys.argv[2])
  File "gscout.py", line 34, in list_projects
    response = request.execute()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/_helpers.py", line 1                                                                                                                                                             33, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/http.py", line 83                                                                                                                                                             8, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://cloudre                                                                                                                                                             sourcemanager.googleapis.com/v1/projects?filter=name%3ACENSOREDPROJ&alt=json                                                                                                                                                              returned "Request had insufficient authentication scopes.">
```

This is basically a fresh Linux machine and the tool fails, are there missing setup steps in the guide, am I missing steps?

**Comment by Sleeptime17** [comment]
The G-Scout steps? No, only partially when I tried to play around with it
after cs-suite didn't work. I assumed cs-suite wraps the setup for G-Scout,
and followed only the intructions in the main readme.

**Comment by shivankar-madaan** [comment]
we haven't wrapped up the setup for G-Scout, being dead honest. I will add the wrap steps for this in the coming future.

**Comment by Sleeptime17** [comment]
Alright, meanwhile I'll set that up separately :)
