### ISSUE TITLE
How tom configure for Azure 

### ISSUE THREAD

**Issue by challs1** [SecurityFTW/cs-suite#21]
I'm trying to run this tool to audit my Azure cloud environment and my server is running in AWSEc2 instance. This is working satisfactorily with AWS. now, i wan to generate same kind of report for azure as well.
Did anybody worked to make this tool to generate the report for Azure cloud ?
i'm getting this error
[ec2-user@ip-172-31-27-131 cs-suite]$ python cs.py -env azure
Traceback (most recent call last):
  File "cs.py", line 55, in <module>
    main()
  File "cs.py", line 50, in main
    from modules import azureaudit
  File "/home/ec2-user/cs-suite/modules/azureaudit.py", line 8, in <module>
    subprocess.call(['az', 'login'])
  File "/usr/lib64/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[ec2-user@ip-172-31-27-131 cs-suite]$

**Comment by shivankar-madaan** [comment]
Hi @challs1 
For azure, the first command `az login` requires a browser interaction to authenticate with Azure subscription
Could try running on your local system, since AWS instances won't have browser capabilities if it is a Linux box.

**Comment by shivankar-madaan** [comment]
@challs1 did it work on the local system.

**Comment by exrme18** [comment]
Hey @challs1 @shivankar-madaan 
can you please tell what exact command do I need to run from command line as I am getting the same error on running following command:
python cs.py -env azure

"For azure, the first command az login requires a browser interaction to authenticate with Azure subscription" What exactly you are referring here.
thanks
