### ISSUE TITLE
Tool does not work

### ISSUE THREAD

**Issue by challs1** [SecurityFTW/cs-suite#29]
I am trying to use it in azure . installed rhel linux server and azure cli but faciing this error while running the report how ever it was generating error for 6.1: Checking if any network group allows public access to RDP and it was getting failed from there

Traceback (most recent call last):
  File "cs.py", line 55, in <module>
    main()
  File "cs.py", line 51, in main
    azureaudit.azure_audit()
  File "/home/challs1/cs-suite/modules/azureaudit.py", line 1572, in azure_audit
    rdp_public()
  File "/home/challs1/cs-suite/modules/azureaudit.py", line 902, in rdp_public
    j_res['value'] = "The network group %s does not allow public RDP access" % network_group
UnboundLocalError: local variable 'j_res' referenced before assignment

**Comment by wstinkens** [comment]
I'm getting the same error.

@challs1 
How did you resolve this?
