### ISSUE TITLE
Azure audit fails when Checking if expiry is enabled for vault secret 

### ISSUE THREAD

**Issue by d1vious** [SecurityFTW/cs-suite#38]
When running a audit for Azure I get the following error:
```
8.2: Checking if expiry is enabled for vault secret

Traceback (most recent call last):
  File "cs.py", line 55, in <module>
    main()
  File "cs.py", line 51, in main
    azureaudit.azure_audit()
  File "/Users/xxx/workspace/cs-suite/modules/azureaudit.py", line 1580, in azure_audit
    vault_secret()
  File "/Users/xxxx/workspace/cs-suite/modules/azureaudit.py", line 1126, in vault_secret
    if key_name == 'Access':
UnboundLocalError: local variable 'key_name' referenced before assignment
```
Looking through the code it seems like https://github.com/SecurityFTW/cs-suite/blob/master/modules/azureaudit.py#L1126 should be checking if the key `Access` exists in the first hand before evaluating it eg ```if "Access" in key_name:```

I am current running of the following commit ID from master:
```commit 0a0ea66305972d20657d9d6a9710eed273e9e44a (HEAD -> master, origin/master, origin/HEAD)
Author: shivankarmadaan <shivankar.madaan@sprinklr.com>
Date:   Thu Dec 6 16:06:28 2018 +0530

    new update```
Current on OSX running current version of master for the app

**Comment by d1vious** [comment]
removing this condition solved the issue `if key_name == 'Access':`

**Comment by shivankar-madaan** [comment]
Closing this issue as this has been merged
